CFLAGS = 
LDFLAGS = -lXm -lXt -lX11

PROGRAMS = titleres titles titles2 possize \
           dialoggeo dialogpos onlydialog getanswer \
           iconbm wmstate closeignore closeunmap closesave \
           mwmhints ismwm mwmmenu sessionsave norestart

all : $(PROGRAMS)

clean :
	-$ rm -f $(PROGRAMS)
