CFLAGS = -g
LDFLAGS =  -lXm -lXt -lX11

PROGRAMS = colorname colorval changecolor rubberband \
           bgpixmap labelpixmap tilepixmap iconpixmap \
           pixmapdraw putimage getimage \
           animtiming animpixmap animplane \
           cliprect addregion inregion

all : $(PROGRAMS)

clean :
	-$ rm -f $(PROGRAMS)
