CFLAGS = -g -Wall
LDFLAGS = -lXm -lXt -lX11

PROGRAMS = textcopy clipboard clipctext cliplength clipincr \
           clipinquire clip2type clipnewform clipstruct clipbyname

all : $(PROGRAMS)

clean :
	-$ rm -f $(PROGRAMS)
