CFLAGS = 
LDFLAGS = -lXm -lXt -lX11

PROGRAMS = atom setprop getprop propnotify proprecv cutbuffer \
           recvxevent sendxevent recvclmsg sendclmsg \
           outputdata inputdata multidisp

all : $(PROGRAMS)

clean :
	-$ rm -f $(PROGRAMS)
